---
title: "Convert membership matrices to crosswalk tables"
author: "Ben Cresswell"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
 html_document:
    code_folding: show
    collapse: no
    df_print: paged
    fig_caption: yes
    fig_height: 6
    fig_width: 10
    highlight: textmate
    theme: spacelab
    toc: yes
    toc_float: yes
editor_options: 
  chunk_output_type: inline
---


```{r setup, include=FALSE}
# Set options, housekeeping
knitr::opts_chunk$set(
	echo = FALSE,
	include = TRUE,
	message = FALSE,
	warning = FALSE)
```


# Introduction
This file converts completed membership matrix templates into crosswalk tables for the Atlas synthesis process.


# Housekeeping
```{r}
# Load required libraries
library(glue) #for string manipulation
library(fs) #for file system operations
library(readxl)  #for reading excel files
library(googlesheets4) #for reading google sheets
library(tidyverse)  #for data wrangling etc
rm(list=ls())
```


# Load efg information
### Pixel values
```{r}
efg_codes <- read_csv(
  "https://raw.githubusercontent.com/Global-Ecosystems-Atlas/metadata/refs/heads/main/pixel-values/efg_pixelvalues.csv",
  show_col_types = FALSE) |>
  rename(efg_code = EFG_Code,
         efg_name = EFG_Name,
         efg_description = EFG,
         pixel_value = PixelValue) |> 
  mutate(efg_code = as.character(efg_code)) |> 
  mutate(efg_code = replace_na(efg_code, "NA")) |> 
  pull(efg_code) |> 
  unique()
```


# Specify input and output directories
```{r}
input_folder <- here::here("resources/02-membership-matrix-complete")
output_folder <- here::here("resources/03_cw_tables_GEA")
dir_create(output_folder)
```


# Function to process membership matrix template for one dataset
```{r}
# Function to process one membership matrix file
process_membmat <- function(file_path) {
  
  # Derive data_id_code from folder name
  data_id <- basename(dirname(file_path))
  
  # Read membership matrix
  dat <- read_csv(file_path, show_col_types = FALSE)
  
  # Pivot longer across all EFG codes
  dat_long <- dat |>
    pivot_longer(
      cols = all_of(efg_codes),
      names_to = "efg_code",
      values_to = "value"
    ) |>
    filter(value == 1) |>
    select(-value)
  
  # Join with metadata
  dat_long <- dat_long |>
    left_join(efg_pixelvalues, by = "efg_code") |>
    select(
      crossref_date,
      crossref_by,
      GET_vsn,
      Source_ID,
      data_id_code,
      band_layer_name,
      in_class_field_name,
      in_class_value,
      in_class_description,
      in_class_description_detail,
      efg_code,
      efg_name,
      efg_description,
      pixel_value
    ) |>
    arrange(data_id_code, band_layer_name, in_class_value)
  
  # Define output subdir and ensure it exists
  sub_dir <- path(output_folder, data_id)
  dir_create(sub_dir)
  
  # Save
  save_path <- path(sub_dir, glue::glue("{data_id}_GEA_crosswalk_table.csv"))
  write_csv(dat_long, save_path)
  
  message("Processed: ", data_id)
}

```

# Process all membership matrix files
```{r}
dir_ls(input_folder, recurse = TRUE, regexp = "-membmat-complete\\.csv$") |>
  walk(process_membmat)
```

